server:
  port: 8088
  servlet:
    context-path: /


spring:
  datasource:
    #    url: jdbc:mysql://localhost:3308/goodgoods02?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    url: jdbc:mysql://localhost:3306/goodgoods02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zd071745
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #      sh
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    database: mysql
    show-sql: true

  logging:
    level:
      cn.com.lc.dao: debug #sql日志打印

  ##设置thymeleaf模版引擎的前后缀（可选项）
  #  spring.thymeleaf.prefix=classpath:/templates/
  #  spring.thymeleaf.suffix=.html
  #
  #  #设置thymeleaf模板引擎的缓存，设置为false关闭，默认为true开启
  #  spring.thymeleaf.cache=false
  ##设置thymeleaf模版引擎的前后缀（可选项）

  thymeleaf:
    prefix: classpath:/
    suffix: .html
    cache: false


  spring:
    mvc:
        static-path-pattern: /**


